version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postmancourseplatzi
      - POSTGRES_USER=postmancourseplatziuser
      - POSTGRES_PASSWORD=dfjhaSDn634fhdbnfuyfjqAhd
  web:
    build: .
    command: tail -F anything
    volumes:
      - ./project:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
